# Altair — the batteries-included web framework for Crystal.
#
# This file defines `Altair::Record::Migrations::SchemaGenerator`, which
# writes `db/schema.cr` from a schema state. The generated file is plain
# Crystal — a `Schema.define` block with typed tables, columns and indexes —
# so it can be `require`d by the application and loaded by the compiler.
# The runner regenerates it after every migrate and rollback.
module Altair
  module Record
    module Migrations
      class SchemaGenerator
        def initialize(@adapter : Adapter, @schema_path : Path)
        end

        # Writes the generated schema file. The parent directory is
        # created when missing.
        def write(schema : Schema) : Nil
          Dir.mkdir_p(@schema_path.parent.to_s)
          File.write(@schema_path, render(schema))
        end

        private def render(schema : Schema) : String
          String.build do |io|
            io << "# db/schema.cr — generated by Altair::Record, do not edit.\n"
            io << "# The source of truth is the migrations; rebuild with the runner.\n"
            io << "Altair::Record::Schema.define do |schema|\n"
            schema.tables.each do |table|
              io << "  schema.table(:#{table.name}) do |t|\n"
              table.columns.each do |column|
                io << "    t.column :#{column.name}, :#{column.type}, null: #{column.null?}, primary: #{column.primary?}\n"
              end
              table.indexes.each do |index|
                io << "    t.index [:"
                io << index.columns.join(", :")
                io << "], unique: #{index.unique?}, name: :#{index.name}\n"
              end
              io << "  end\n"
            end
            io << "end\n"
          end
        end
      end
    end
  end
end
