# db/schema.cr — generated by Altair::Record, do not edit.
# The source of truth is the migrations; rebuild with the runner.
class Altair::Record::Schema
  # Compile-time column metadata consumed by Altair::Record::Model macros.
  META = {
    products: {
      id:         {type: :integer, null: false, primary: true},
      name:       {type: :string, null: false, primary: false},
      price:      {type: :float, null: false, primary: false},
      created_at: {type: :datetime, null: true, primary: false},
      updated_at: {type: :datetime, null: true, primary: false},
    },
  }
end
Altair::Record::Schema.define do |schema|
  schema.table(:products) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :name, :string, null: false, primary: false
    t.column :price, :float, null: false, primary: false
    t.column :created_at, :datetime, null: true, primary: false
    t.column :updated_at, :datetime, null: true, primary: false
  end
end
