# db/schema.cr — generated by Altair::Record, do not edit.
# The source of truth is the migrations; rebuild with the runner.
class Altair::Record::Schema
  # Compile-time column metadata consumed by Altair::Record::Model macros.
  META = {
    users: {
      id:         {type: :integer, null: false, primary: true},
      name:       {type: :string, null: true, primary: false},
      email:      {type: :string, null: true, primary: false},
      password:   {type: :string, null: true, primary: false},
      created_at: {type: :datetime, null: true, primary: false},
      updated_at: {type: :datetime, null: true, primary: false},
    },
    posts: {
      id:         {type: :integer, null: false, primary: true},
      title:      {type: :string, null: true, primary: false},
      body:       {type: :text, null: true, primary: false},
      image:      {type: :string, null: true, primary: false},
      published:  {type: :boolean, null: true, primary: false},
      user_id:    {type: :integer, null: true, primary: false},
      created_at: {type: :datetime, null: true, primary: false},
      updated_at: {type: :datetime, null: true, primary: false},
    },
    comments: {
      id:         {type: :integer, null: false, primary: true},
      body:       {type: :text, null: true, primary: false},
      post_id:    {type: :integer, null: true, primary: false},
      user_id:    {type: :integer, null: true, primary: false},
      created_at: {type: :datetime, null: true, primary: false},
      updated_at: {type: :datetime, null: true, primary: false},
    },
  }
end

Altair::Record::Schema.define do |schema|
  schema.table(:users) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :name, :string, null: true, primary: false
    t.column :email, :string, null: true, primary: false
    t.column :password, :string, null: true, primary: false
    t.column :created_at, :datetime, null: true, primary: false
    t.column :updated_at, :datetime, null: true, primary: false
  end
  schema.table(:posts) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :title, :string, null: true, primary: false
    t.column :body, :text, null: true, primary: false
    t.column :image, :string, null: true, primary: false
    t.column :published, :boolean, null: true, primary: false
    t.column :user_id, :integer, null: true, primary: false
    t.column :created_at, :datetime, null: true, primary: false
    t.column :updated_at, :datetime, null: true, primary: false
    t.index [:user_id], unique: false, name: "index_posts_on_user_id"
  end
  schema.table(:comments) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :body, :text, null: true, primary: false
    t.column :post_id, :integer, null: true, primary: false
    t.column :user_id, :integer, null: true, primary: false
    t.column :created_at, :datetime, null: true, primary: false
    t.column :updated_at, :datetime, null: true, primary: false
    t.index [:post_id], unique: false, name: "index_comments_on_post_id"
    t.index [:user_id], unique: false, name: "index_comments_on_user_id"
  end
end
