# Altair — the batteries-included web framework for Crystal.
#
# This file defines the scaffold generator: `altair generate scaffold Post
# title:string body:text` writes the model, the `Create<Table>` migration
# and the RESTful controller+views, then inserts `resources :posts` into
# the routes block. It is the full vertical slice: new project, scaffold,
# server — and the demo works.
module Altair
  module CLI
    module Generators
      class Scaffold
        include Base

        # The resource name argument, e.g. `Post`.
        getter name : String

        # The columns of the scaffolded resource.
        getter columns : Array(Column)

        def initialize(@name : String, @columns : Array(Column))
        end

        # The resource path name, e.g. `posts`.
        def table : String
          tableize(classify(@name))
        end

        # Writes the model, migration and controller/views, registers the
        # `resources` route and seeds `db/schema.cr`. Returns the paths.
        def generate : Array(Path)
          paths = [] of Path

          model = Model.new(name)
          paths << model.generate

          migration = Migration.new("Create#{Altair::Inflector.pluralize(classify(@name))}", columns)
          paths << migration.generate

          controller = Controller.new(name, Controller::DEFAULT_ACTIONS, columns)
          paths << controller.generate

          seed_schema(table)
          register_routes(table)
          paths
        end

        # Appends the scaffolded table to `db/schema.cr` so the model
        # compiles before the first migration runs. Preserves any tables
        # already declared; regenerating is idempotent. Returns the path.
        def seed_schema(table : String) : Path
          path = Path.new("db/schema.cr")
          existing = read_tables(File.exists?(path) ? File.read(path) : "")

          if existing.any? { |name, _| name == table }
            return path
          end
          existing << {table, columns_with_id}
          write_file(path, render_schema(existing))
        end

        # The table's columns, the primary `id` first.
        private def columns_with_id : Array(Column)
          [Column.new("id", :integer)] + @columns
        end

        # Parses the declared tables out of an existing `db/schema.cr`
        # (`name`, columns) from its `Schema.define` block.
        private def read_tables(content : String) : Array(Tuple(String, Array(Column)))
          tables = [] of Tuple(String, Array(Column))
          content.scan(/schema\.table\(:(\w+)\) do \|t\|\n((?:\s+\S.*\n)*?)\s+end/) do |match|
            name = match[1]
            cols = [] of Column
            match[2].split('\n').each do |line|
              if line =~ /\s+t\.column :(\w+), :(\w+)/
                cols << Column.new($1, TYPE_NAMES[$2])
              end
            end
            cols.unshift(Column.new("id", :integer)) unless cols.any?(&.name.==("id"))
            tables << {name, cols}
          end
          tables
        end

        # Maps a schema type name to its symbol (`"integer"` → `:integer`).
        private TYPE_NAMES = Base::VALID_TYPES.to_h { |t| {t.to_s, t} }

        # Renders `db/schema.cr`, matching the runner's own output so a
        # later `db:migrate` produces identical bytes.
        private def render_schema(tables : Array(Tuple(String, Array(Column)))) : String
          String.build do |io|
            io << "# db/schema.cr — generated by Altair::Record, do not edit.\n"
            io << "# The source of truth is the migrations; rebuild with the runner.\n"
            io << "class Altair::Record::Schema\n"
            io << "  # Compile-time column metadata consumed by Altair::Record::Model macros.\n"
            io << "  META = {\n"
            tables.each do |table_name, cols|
              io << "    #{table_name}: {\n"
              max = cols.max_of(&.name.size)
              cols.each do |col|
                col_name = col.name + ":"
                meta = col.name == "id" ? "null: false, primary: true" : "null: true, primary: false"
                io << "      #{(col_name).ljust(max + 1)} {type: :#{col.type}, #{meta}},\n"
              end
              io << "    },\n"
            end
            io << "  }\n"
            io << "end\n"
            io << "\n"
            io << "Altair::Record::Schema.define do |schema|\n"
            tables.each do |table_name, cols|
              io << "  schema.table(:#{table_name}) do |t|\n"
              cols.each do |col|
                null = col.name == "id" ? "null: false, primary: true" : "null: true, primary: false"
                io << "    t.column :#{col.name}, :#{col.type}, #{null}\n"
              end
              io << "  end\n"
            end
            io << "end\n"
          end
        end

        # Inserts `resources :posts` into the `routes do` block, respecting
        # indentation. Regenerating is idempotent. Returns the routes path.
        def register_routes(table : String) : Path
          path = Path.new("src/config/routes.cr")
          lines = File.read_lines(path)

          if lines.any?(&.includes?("resources :#{table}"))
            return path
          end

          open = lines.index(&.includes?("routes do"))
          close = open.try { |i| (i + 1...lines.size).find { |j| lines[j].strip == "end" } }
          unless open && close
            raise Altair::Error.new("Could not find a `routes do` block in #{path}")
          end

          body_indent = lines[open].gsub(/\S.*/, "").size + 2
          lines.insert(close, "#{" " * body_indent}resources :#{table}")
          write_file(path, lines.join('\n'))
        end
      end
    end
  end
end
