# db/schema.cr — generated by Altair::Record, do not edit.
# The source of truth is the migrations; rebuild with the runner.
Altair::Record::Schema.define do |schema|
  schema.table(:posts) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :title, :string, null: true, primary: false
    t.column :body, :text, null: true, primary: false
  end
  schema.table(:comments) do |t|
    t.column :id, :integer, null: false, primary: true
    t.column :body, :string, null: true, primary: false
    t.column :post_id, :integer, null: true, primary: false
    t.index [:post_id], unique: false, name: :index_comments_on_post_id
  end
end
