# Altair — the batteries-included web framework for Crystal.
#
# This is the framework's entry point. Requiring `altair` loads every
# component of the framework in dependency order: the exception hierarchy,
# the configuration system, the support utilities, the HTTP abstractions, the
# application core and finally the server. Applications never require
# individual files — they require this single entry point and the compiler
# resolves the rest.
module Altair
end

require "http/server"
require "uri"
require "db"
require "json"
require "big"
require "sqlite3"
require "random/secure"
require "crypto/subtle"

require "./altair/core/version"
require "./altair/exceptions/error"
require "./altair/exceptions/configuration_error"
require "./altair/exceptions/http_error"
require "./altair/exceptions/method_not_allowed"
require "./altair/exceptions/payload_too_large"
require "./altair/exceptions/invalid_csrf_token"
require "./altair/exceptions/unauthorized"
require "./altair/support/ansi"
require "./altair/support/inflector"
require "./altair/support/lru_cache"
require "./altair/config/env"
require "./altair/config/environments/base"
require "./altair/config/config"
require "./altair/config/dotenv"
require "./altair/config/database"
require "./altair/http/uploaded_file"
require "./altair/http/params"
require "./altair/http/request"
require "./altair/http/response"
require "./altair/session/store"
require "./altair/session/session"
require "./altair/session/flash"
require "./altair/auth/jwt"
require "./altair/view/htmx"
require "./altair/view/template"
require "./altair/view/helpers"
require "./altair/view/form_builder"
require "./altair/controller/base"
require "./altair/controller/callbacks"
require "./altair/controller/rescue_from"
require "./altair/controller/respond_to"
require "./altair/middleware/base"
require "./altair/middleware/logger"
require "./altair/middleware/request_id"
require "./altair/middleware/security_headers"
require "./altair/middleware/cors"
require "./altair/middleware/static"
require "./altair/routing/segment"
require "./altair/routing/route"
require "./altair/routing/route_set"
require "./altair/routing/router"
require "./altair/core/error_handlers"
require "./altair/core/error_pages"
require "./altair/core/request_handler"
require "./altair/core/application"
require "./altair/routing/dsl"
require "./altair/concurrency/semaphore"
require "./altair/record/adapter"
require "./altair/record/adapters/sqlite3"
require "./altair/record/schema"
require "./altair/record/connection"
require "./altair/record/migrations/migration"
require "./altair/record/migrations/runner"
require "./altair/record/migrations/schema_generator"
require "./altair/record/record"
require "./altair/record/model"
require "./altair/record/relation"
require "./altair/record/association"
require "./altair/record/n_detector"
require "./altair/record/permit_gate"
require "./altair/cli/cli"
require "./altair/cli/install"
require "./altair/cli/update"
require "./altair/cli/project"
require "./altair/cli/generators"
require "./altair/cli/generators/base"
require "./altair/cli/generators/model"
require "./altair/cli/generators/migration"
require "./altair/cli/generators/controller"
require "./altair/cli/generators/scaffold"
require "./altair/cli/generators/new"
require "./altair/server/server"
require "./altair/testing/test"
